{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Test Codebase Here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ['CUDA_VISIBLE_DEVICES']='2,3,4' "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/trl/trainer/ppo_config.py:141: UserWarning: The `optimize_cuda_cache` arguement will be deprecated soon, please use `optimize_device_cache` instead.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from rl_jailbreak.models.model import load_generator, load_target, load_reward\n",
    "import torch\n",
    "torch.cuda.is_available()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "torch.cuda.current_device()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "ename": "DeferredCudaCallError",
     "evalue": "CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at \"../aten/src/ATen/cuda/CUDAContext.cpp\":50, please report a bug to PyTorch. \n\nCUDA call was originally invoked at:\n\n['  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\\n    return _run_code(code, main_globals, None,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 86, in _run_code\\n    exec(code, run_globals)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\\n    app.launch_new_instance()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/traitlets/config/application.py\", line 1077, in launch_instance\\n    app.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 737, in start\\n    self.io_loop.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\\n    self.asyncio_loop.run_forever()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 595, in run_forever\\n    self._run_once()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 1881, in _run_once\\n    handle._run()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/events.py\", line 80, in _run\\n    self._context.run(self._callback, *self._args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 524, in dispatch_queue\\n    await self.process_one()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 513, in process_one\\n    await dispatch(*args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 418, in dispatch_shell\\n    await result\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 758, in execute_request\\n    reply_content = await reply_content\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 426, in do_execute\\n    res = shell.run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\\n    return super().run_cell(*args, **kwargs)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\\n    result = self._run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\\n    result = runner(coro)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\\n    coro.send(None)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\\n    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\\n    if await self.run_code(code, result, async_=asy):\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\\n    exec(code_obj, self.user_global_ns, self.user_ns)\\n', '  File \"/tmp/ipykernel_2726929/158012258.py\", line 1, in <module>\\n    from rl_jailbreak.models.model import load_generator, load_target, load_reward\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/__init__.py\", line 1, in <module>\\n    from .reward_model import ToxicityModel\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/reward_model.py\", line 2, in <module>\\n    from transformers import AutoTokenizer, AutoModelForSequenceClassification\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/__init__.py\", line 26, in <module>\\n    from . import dependency_versions_check\\n', '  File \"<frozen importlib._bootstrap>\", line 1078, in _handle_fromlist\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/dependency_versions_check.py\", line 16, in <module>\\n    from .utils.versions import require_version, require_version_core\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/__init__.py\", line 31, in <module>\\n    from .generic import (\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/generic.py\", line 432, in <module>\\n    import torch.utils._pytree as _torch_pytree\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/__init__.py\", line 1146, in <module>\\n    _C._initExtension(manager_path())\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 197, in <module>\\n    _lazy_call(_check_capability)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 195, in _lazy_call\\n    _queued_calls.append((callable, traceback.format_stack()))\\n']",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:260\u001b[0m, in \u001b[0;36m_lazy_init\u001b[0;34m()\u001b[0m\n\u001b[1;32m    259\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 260\u001b[0m     queued_call()\n\u001b[1;32m    261\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:145\u001b[0m, in \u001b[0;36m_check_capability\u001b[0;34m()\u001b[0m\n\u001b[1;32m    144\u001b[0m \u001b[39mfor\u001b[39;00m d \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(device_count()):\n\u001b[0;32m--> 145\u001b[0m     capability \u001b[39m=\u001b[39m get_device_capability(d)\n\u001b[1;32m    146\u001b[0m     major \u001b[39m=\u001b[39m capability[\u001b[39m0\u001b[39m]\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:381\u001b[0m, in \u001b[0;36mget_device_capability\u001b[0;34m(device)\u001b[0m\n\u001b[1;32m    369\u001b[0m \u001b[39m\u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Gets the cuda capability of a device.\u001b[39;00m\n\u001b[1;32m    370\u001b[0m \n\u001b[1;32m    371\u001b[0m \u001b[39mArgs:\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    379\u001b[0m \u001b[39m    tuple(int, int): the major and minor cuda capability of the device\u001b[39;00m\n\u001b[1;32m    380\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m--> 381\u001b[0m prop \u001b[39m=\u001b[39m get_device_properties(device)\n\u001b[1;32m    382\u001b[0m \u001b[39mreturn\u001b[39;00m prop\u001b[39m.\u001b[39mmajor, prop\u001b[39m.\u001b[39mminor\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:399\u001b[0m, in \u001b[0;36mget_device_properties\u001b[0;34m(device)\u001b[0m\n\u001b[1;32m    398\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mAssertionError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mInvalid device id\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> 399\u001b[0m \u001b[39mreturn\u001b[39;00m _get_device_properties(device)\n",
      "\u001b[0;31mRuntimeError\u001b[0m: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at \"../aten/src/ATen/cuda/CUDAContext.cpp\":50, please report a bug to PyTorch. ",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mDeferredCudaCallError\u001b[0m                     Traceback (most recent call last)",
      "\u001b[1;32m/data/nzxyin/rl_jailbreak/test.ipynb Cell 4\u001b[0m line \u001b[0;36m1\n\u001b[0;32m----> <a href='vscode-notebook-cell://ssh-remote%2Bvox.eecs.berkeley.edu/data/nzxyin/rl_jailbreak/test.ipynb#W5sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'>1</a>\u001b[0m torch\u001b[39m.\u001b[39;49mcuda\u001b[39m.\u001b[39;49mget_device_capability(\u001b[39m0\u001b[39;49m)\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:381\u001b[0m, in \u001b[0;36mget_device_capability\u001b[0;34m(device)\u001b[0m\n\u001b[1;32m    368\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget_device_capability\u001b[39m(device: Optional[_device_t] \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Tuple[\u001b[39mint\u001b[39m, \u001b[39mint\u001b[39m]:\n\u001b[1;32m    369\u001b[0m \u001b[39m    \u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Gets the cuda capability of a device.\u001b[39;00m\n\u001b[1;32m    370\u001b[0m \n\u001b[1;32m    371\u001b[0m \u001b[39m    Args:\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    379\u001b[0m \u001b[39m        tuple(int, int): the major and minor cuda capability of the device\u001b[39;00m\n\u001b[1;32m    380\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 381\u001b[0m     prop \u001b[39m=\u001b[39m get_device_properties(device)\n\u001b[1;32m    382\u001b[0m     \u001b[39mreturn\u001b[39;00m prop\u001b[39m.\u001b[39mmajor, prop\u001b[39m.\u001b[39mminor\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:395\u001b[0m, in \u001b[0;36mget_device_properties\u001b[0;34m(device)\u001b[0m\n\u001b[1;32m    385\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget_device_properties\u001b[39m(device: _device_t) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m _CudaDeviceProperties:\n\u001b[1;32m    386\u001b[0m \u001b[39m    \u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Gets the properties of a device.\u001b[39;00m\n\u001b[1;32m    387\u001b[0m \n\u001b[1;32m    388\u001b[0m \u001b[39m    Args:\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    393\u001b[0m \u001b[39m        _CudaDeviceProperties: the properties of the device\u001b[39;00m\n\u001b[1;32m    394\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 395\u001b[0m     _lazy_init()  \u001b[39m# will define _get_device_properties\u001b[39;00m\n\u001b[1;32m    396\u001b[0m     device \u001b[39m=\u001b[39m _get_device_index(device, optional\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n\u001b[1;32m    397\u001b[0m     \u001b[39mif\u001b[39;00m device \u001b[39m<\u001b[39m \u001b[39m0\u001b[39m \u001b[39mor\u001b[39;00m device \u001b[39m>\u001b[39m\u001b[39m=\u001b[39m device_count():\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:264\u001b[0m, in \u001b[0;36m_lazy_init\u001b[0;34m()\u001b[0m\n\u001b[1;32m    261\u001b[0m         \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    262\u001b[0m             msg \u001b[39m=\u001b[39m (\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mCUDA call failed lazily at initialization with error: \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mstr\u001b[39m(e)\u001b[39m}\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    263\u001b[0m                    \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mCUDA call was originally invoked at:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00morig_traceback\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> 264\u001b[0m             \u001b[39mraise\u001b[39;00m DeferredCudaCallError(msg) \u001b[39mfrom\u001b[39;00m \u001b[39me\u001b[39;00m\n\u001b[1;32m    265\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    266\u001b[0m     \u001b[39mdelattr\u001b[39m(_tls, \u001b[39m'\u001b[39m\u001b[39mis_initializing\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[0;31mDeferredCudaCallError\u001b[0m: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at \"../aten/src/ATen/cuda/CUDAContext.cpp\":50, please report a bug to PyTorch. \n\nCUDA call was originally invoked at:\n\n['  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\\n    return _run_code(code, main_globals, None,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 86, in _run_code\\n    exec(code, run_globals)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\\n    app.launch_new_instance()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/traitlets/config/application.py\", line 1077, in launch_instance\\n    app.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 737, in start\\n    self.io_loop.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\\n    self.asyncio_loop.run_forever()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 595, in run_forever\\n    self._run_once()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 1881, in _run_once\\n    handle._run()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/events.py\", line 80, in _run\\n    self._context.run(self._callback, *self._args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 524, in dispatch_queue\\n    await self.process_one()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 513, in process_one\\n    await dispatch(*args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 418, in dispatch_shell\\n    await result\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 758, in execute_request\\n    reply_content = await reply_content\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 426, in do_execute\\n    res = shell.run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\\n    return super().run_cell(*args, **kwargs)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\\n    result = self._run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\\n    result = runner(coro)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\\n    coro.send(None)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\\n    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\\n    if await self.run_code(code, result, async_=asy):\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\\n    exec(code_obj, self.user_global_ns, self.user_ns)\\n', '  File \"/tmp/ipykernel_2726929/158012258.py\", line 1, in <module>\\n    from rl_jailbreak.models.model import load_generator, load_target, load_reward\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/__init__.py\", line 1, in <module>\\n    from .reward_model import ToxicityModel\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/reward_model.py\", line 2, in <module>\\n    from transformers import AutoTokenizer, AutoModelForSequenceClassification\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/__init__.py\", line 26, in <module>\\n    from . import dependency_versions_check\\n', '  File \"<frozen importlib._bootstrap>\", line 1078, in _handle_fromlist\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/dependency_versions_check.py\", line 16, in <module>\\n    from .utils.versions import require_version, require_version_core\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/__init__.py\", line 31, in <module>\\n    from .generic import (\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/generic.py\", line 432, in <module>\\n    import torch.utils._pytree as _torch_pytree\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/__init__.py\", line 1146, in <module>\\n    _C._initExtension(manager_path())\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 197, in <module>\\n    _lazy_call(_check_capability)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 195, in _lazy_call\\n    _queued_calls.append((callable, traceback.format_stack()))\\n']"
     ]
    }
   ],
   "source": [
    "torch.cuda.get_device_capability(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "ename": "DeferredCudaCallError",
     "evalue": "CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at \"../aten/src/ATen/cuda/CUDAContext.cpp\":50, please report a bug to PyTorch. \n\nCUDA call was originally invoked at:\n\n['  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\\n    return _run_code(code, main_globals, None,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 86, in _run_code\\n    exec(code, run_globals)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\\n    app.launch_new_instance()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/traitlets/config/application.py\", line 1077, in launch_instance\\n    app.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 737, in start\\n    self.io_loop.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\\n    self.asyncio_loop.run_forever()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 595, in run_forever\\n    self._run_once()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 1881, in _run_once\\n    handle._run()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/events.py\", line 80, in _run\\n    self._context.run(self._callback, *self._args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 524, in dispatch_queue\\n    await self.process_one()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 513, in process_one\\n    await dispatch(*args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 418, in dispatch_shell\\n    await result\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 758, in execute_request\\n    reply_content = await reply_content\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 426, in do_execute\\n    res = shell.run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\\n    return super().run_cell(*args, **kwargs)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\\n    result = self._run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\\n    result = runner(coro)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\\n    coro.send(None)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\\n    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\\n    if await self.run_code(code, result, async_=asy):\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\\n    exec(code_obj, self.user_global_ns, self.user_ns)\\n', '  File \"/tmp/ipykernel_2726929/158012258.py\", line 1, in <module>\\n    from rl_jailbreak.models.model import load_generator, load_target, load_reward\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/__init__.py\", line 1, in <module>\\n    from .reward_model import ToxicityModel\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/reward_model.py\", line 2, in <module>\\n    from transformers import AutoTokenizer, AutoModelForSequenceClassification\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/__init__.py\", line 26, in <module>\\n    from . import dependency_versions_check\\n', '  File \"<frozen importlib._bootstrap>\", line 1078, in _handle_fromlist\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/dependency_versions_check.py\", line 16, in <module>\\n    from .utils.versions import require_version, require_version_core\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/__init__.py\", line 31, in <module>\\n    from .generic import (\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/generic.py\", line 432, in <module>\\n    import torch.utils._pytree as _torch_pytree\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/__init__.py\", line 1146, in <module>\\n    _C._initExtension(manager_path())\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 197, in <module>\\n    _lazy_call(_check_capability)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 195, in _lazy_call\\n    _queued_calls.append((callable, traceback.format_stack()))\\n']",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:260\u001b[0m, in \u001b[0;36m_lazy_init\u001b[0;34m()\u001b[0m\n\u001b[1;32m    259\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 260\u001b[0m     queued_call()\n\u001b[1;32m    261\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:145\u001b[0m, in \u001b[0;36m_check_capability\u001b[0;34m()\u001b[0m\n\u001b[1;32m    144\u001b[0m \u001b[39mfor\u001b[39;00m d \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(device_count()):\n\u001b[0;32m--> 145\u001b[0m     capability \u001b[39m=\u001b[39m get_device_capability(d)\n\u001b[1;32m    146\u001b[0m     major \u001b[39m=\u001b[39m capability[\u001b[39m0\u001b[39m]\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:381\u001b[0m, in \u001b[0;36mget_device_capability\u001b[0;34m(device)\u001b[0m\n\u001b[1;32m    369\u001b[0m \u001b[39m\u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Gets the cuda capability of a device.\u001b[39;00m\n\u001b[1;32m    370\u001b[0m \n\u001b[1;32m    371\u001b[0m \u001b[39mArgs:\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    379\u001b[0m \u001b[39m    tuple(int, int): the major and minor cuda capability of the device\u001b[39;00m\n\u001b[1;32m    380\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m--> 381\u001b[0m prop \u001b[39m=\u001b[39m get_device_properties(device)\n\u001b[1;32m    382\u001b[0m \u001b[39mreturn\u001b[39;00m prop\u001b[39m.\u001b[39mmajor, prop\u001b[39m.\u001b[39mminor\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:399\u001b[0m, in \u001b[0;36mget_device_properties\u001b[0;34m(device)\u001b[0m\n\u001b[1;32m    398\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mAssertionError\u001b[39;00m(\u001b[39m\"\u001b[39m\u001b[39mInvalid device id\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> 399\u001b[0m \u001b[39mreturn\u001b[39;00m _get_device_properties(device)\n",
      "\u001b[0;31mRuntimeError\u001b[0m: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at \"../aten/src/ATen/cuda/CUDAContext.cpp\":50, please report a bug to PyTorch. ",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mDeferredCudaCallError\u001b[0m                     Traceback (most recent call last)",
      "\u001b[1;32m/data/nzxyin/rl_jailbreak/test.ipynb Cell 5\u001b[0m line \u001b[0;36m1\n\u001b[0;32m----> <a href='vscode-notebook-cell://ssh-remote%2Bvox.eecs.berkeley.edu/data/nzxyin/rl_jailbreak/test.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'>1</a>\u001b[0m generator \u001b[39m=\u001b[39m load_generator(\u001b[39m\"\u001b[39;49m\u001b[39mgpt2-medium\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n",
      "File \u001b[0;32m/data/nzxyin/rl_jailbreak/rl_jailbreak/models/model.py:7\u001b[0m, in \u001b[0;36mload_generator\u001b[0;34m(generator_name)\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mload_generator\u001b[39m(generator_name):\n\u001b[1;32m      6\u001b[0m     tokenizer \u001b[39m=\u001b[39m AutoTokenizer\u001b[39m.\u001b[39mfrom_pretrained(generator_name)\n\u001b[0;32m----> 7\u001b[0m     model \u001b[39m=\u001b[39m AutoModelForCausalLMWithValueHead\u001b[39m.\u001b[39;49mfrom_pretrained(generator_name, device_map\u001b[39m=\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39mauto\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n\u001b[1;32m      8\u001b[0m     \u001b[39mreturn\u001b[39;00m GeneratorModel(model, tokenizer,)\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/trl/models/modeling_base.py:205\u001b[0m, in \u001b[0;36mPreTrainedModelWrapper.from_pretrained\u001b[0;34m(cls, pretrained_model_name_or_path, *model_args, **kwargs)\u001b[0m\n\u001b[1;32m    203\u001b[0m     logging\u001b[39m.\u001b[39minfo(\u001b[39m\"\u001b[39m\u001b[39mTrained peft adapter loaded\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    204\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m--> 205\u001b[0m     pretrained_model \u001b[39m=\u001b[39m \u001b[39mcls\u001b[39;49m\u001b[39m.\u001b[39;49mtransformers_parent_class\u001b[39m.\u001b[39;49mfrom_pretrained(\n\u001b[1;32m    206\u001b[0m         pretrained_model_name_or_path, \u001b[39m*\u001b[39;49mmodel_args, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mpretrained_kwargs\n\u001b[1;32m    207\u001b[0m     )\n\u001b[1;32m    209\u001b[0m     \u001b[39mif\u001b[39;00m peft_config \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m    210\u001b[0m         \u001b[39m# Initialize a new peft adapter with the given config\u001b[39;00m\n\u001b[1;32m    211\u001b[0m         \u001b[39mif\u001b[39;00m is_loaded_in_8bit \u001b[39mor\u001b[39;00m is_loaded_in_4bit:\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:566\u001b[0m, in \u001b[0;36m_BaseAutoModelClass.from_pretrained\u001b[0;34m(cls, pretrained_model_name_or_path, *model_args, **kwargs)\u001b[0m\n\u001b[1;32m    564\u001b[0m \u001b[39melif\u001b[39;00m \u001b[39mtype\u001b[39m(config) \u001b[39min\u001b[39;00m \u001b[39mcls\u001b[39m\u001b[39m.\u001b[39m_model_mapping\u001b[39m.\u001b[39mkeys():\n\u001b[1;32m    565\u001b[0m     model_class \u001b[39m=\u001b[39m _get_model_class(config, \u001b[39mcls\u001b[39m\u001b[39m.\u001b[39m_model_mapping)\n\u001b[0;32m--> 566\u001b[0m     \u001b[39mreturn\u001b[39;00m model_class\u001b[39m.\u001b[39;49mfrom_pretrained(\n\u001b[1;32m    567\u001b[0m         pretrained_model_name_or_path, \u001b[39m*\u001b[39;49mmodel_args, config\u001b[39m=\u001b[39;49mconfig, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mhub_kwargs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs\n\u001b[1;32m    568\u001b[0m     )\n\u001b[1;32m    569\u001b[0m \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\n\u001b[1;32m    570\u001b[0m     \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mUnrecognized configuration class \u001b[39m\u001b[39m{\u001b[39;00mconfig\u001b[39m.\u001b[39m\u001b[39m__class__\u001b[39m\u001b[39m}\u001b[39;00m\u001b[39m for this kind of AutoModel: \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mcls\u001b[39m\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m\u001b[39m}\u001b[39;00m\u001b[39m.\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    571\u001b[0m     \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mModel type should be one of \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m, \u001b[39m\u001b[39m'\u001b[39m\u001b[39m.\u001b[39mjoin(c\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m\u001b[39m \u001b[39m\u001b[39mfor\u001b[39;00m\u001b[39m \u001b[39mc\u001b[39m \u001b[39m\u001b[39min\u001b[39;00m\u001b[39m \u001b[39m\u001b[39mcls\u001b[39m\u001b[39m.\u001b[39m_model_mapping\u001b[39m.\u001b[39mkeys())\u001b[39m}\u001b[39;00m\u001b[39m.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m    572\u001b[0m )\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/modeling_utils.py:3396\u001b[0m, in \u001b[0;36mPreTrainedModel.from_pretrained\u001b[0;34m(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)\u001b[0m\n\u001b[1;32m   3391\u001b[0m     logger\u001b[39m.\u001b[39mwarning(\n\u001b[1;32m   3392\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mThis model has some weights that should be kept in higher precision, you need to upgrade \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   3393\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39m`accelerate` to properly deal with them (`pip install --upgrade accelerate`).\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   3394\u001b[0m     )\n\u001b[1;32m   3395\u001b[0m \u001b[39mif\u001b[39;00m device_map \u001b[39m!=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39msequential\u001b[39m\u001b[39m\"\u001b[39m:\n\u001b[0;32m-> 3396\u001b[0m     max_memory \u001b[39m=\u001b[39m get_balanced_memory(\n\u001b[1;32m   3397\u001b[0m         model,\n\u001b[1;32m   3398\u001b[0m         dtype\u001b[39m=\u001b[39;49mtarget_dtype,\n\u001b[1;32m   3399\u001b[0m         low_zero\u001b[39m=\u001b[39;49m(device_map \u001b[39m==\u001b[39;49m \u001b[39m\"\u001b[39;49m\u001b[39mbalanced_low_0\u001b[39;49m\u001b[39m\"\u001b[39;49m),\n\u001b[1;32m   3400\u001b[0m         max_memory\u001b[39m=\u001b[39;49mmax_memory,\n\u001b[1;32m   3401\u001b[0m         \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mdevice_map_kwargs,\n\u001b[1;32m   3402\u001b[0m     )\n\u001b[1;32m   3403\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   3404\u001b[0m     max_memory \u001b[39m=\u001b[39m get_max_memory(max_memory)\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/accelerate/utils/modeling.py:807\u001b[0m, in \u001b[0;36mget_balanced_memory\u001b[0;34m(model, max_memory, no_split_module_classes, dtype, special_dtypes, low_zero)\u001b[0m\n\u001b[1;32m    805\u001b[0m \u001b[39m# Get default / clean up max_memory\u001b[39;00m\n\u001b[1;32m    806\u001b[0m user_not_set_max_memory \u001b[39m=\u001b[39m max_memory \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m--> 807\u001b[0m max_memory \u001b[39m=\u001b[39m get_max_memory(max_memory)\n\u001b[1;32m    809\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m is_xpu_available():\n\u001b[1;32m    810\u001b[0m     num_devices \u001b[39m=\u001b[39m \u001b[39mlen\u001b[39m([d \u001b[39mfor\u001b[39;00m d \u001b[39min\u001b[39;00m max_memory \u001b[39mif\u001b[39;00m torch\u001b[39m.\u001b[39mdevice(d)\u001b[39m.\u001b[39mtype \u001b[39m==\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mcuda\u001b[39m\u001b[39m\"\u001b[39m \u001b[39mand\u001b[39;00m max_memory[d] \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m])\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/accelerate/utils/modeling.py:679\u001b[0m, in \u001b[0;36mget_max_memory\u001b[0;34m(max_memory)\u001b[0m\n\u001b[1;32m    677\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m is_xpu_available():\n\u001b[1;32m    678\u001b[0m     \u001b[39mfor\u001b[39;00m i \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(torch\u001b[39m.\u001b[39mcuda\u001b[39m.\u001b[39mdevice_count()):\n\u001b[0;32m--> 679\u001b[0m         _ \u001b[39m=\u001b[39m torch\u001b[39m.\u001b[39;49mtensor([\u001b[39m0\u001b[39;49m], device\u001b[39m=\u001b[39;49mi)\n\u001b[1;32m    680\u001b[0m     max_memory \u001b[39m=\u001b[39m {i: torch\u001b[39m.\u001b[39mcuda\u001b[39m.\u001b[39mmem_get_info(i)[\u001b[39m0\u001b[39m] \u001b[39mfor\u001b[39;00m i \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(torch\u001b[39m.\u001b[39mcuda\u001b[39m.\u001b[39mdevice_count())}\n\u001b[1;32m    681\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[0;32m~/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py:264\u001b[0m, in \u001b[0;36m_lazy_init\u001b[0;34m()\u001b[0m\n\u001b[1;32m    261\u001b[0m         \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    262\u001b[0m             msg \u001b[39m=\u001b[39m (\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mCUDA call failed lazily at initialization with error: \u001b[39m\u001b[39m{\u001b[39;00m\u001b[39mstr\u001b[39m(e)\u001b[39m}\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m    263\u001b[0m                    \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mCUDA call was originally invoked at:\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\\n\u001b[39;00m\u001b[39m{\u001b[39;00morig_traceback\u001b[39m}\u001b[39;00m\u001b[39m\"\u001b[39m)\n\u001b[0;32m--> 264\u001b[0m             \u001b[39mraise\u001b[39;00m DeferredCudaCallError(msg) \u001b[39mfrom\u001b[39;00m \u001b[39me\u001b[39;00m\n\u001b[1;32m    265\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    266\u001b[0m     \u001b[39mdelattr\u001b[39m(_tls, \u001b[39m'\u001b[39m\u001b[39mis_initializing\u001b[39m\u001b[39m'\u001b[39m)\n",
      "\u001b[0;31mDeferredCudaCallError\u001b[0m: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at \"../aten/src/ATen/cuda/CUDAContext.cpp\":50, please report a bug to PyTorch. \n\nCUDA call was originally invoked at:\n\n['  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\\n    return _run_code(code, main_globals, None,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/runpy.py\", line 86, in _run_code\\n    exec(code, run_globals)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\\n    app.launch_new_instance()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/traitlets/config/application.py\", line 1077, in launch_instance\\n    app.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 737, in start\\n    self.io_loop.start()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 199, in start\\n    self.asyncio_loop.run_forever()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 595, in run_forever\\n    self._run_once()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/base_events.py\", line 1881, in _run_once\\n    handle._run()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/asyncio/events.py\", line 80, in _run\\n    self._context.run(self._callback, *self._args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 524, in dispatch_queue\\n    await self.process_one()\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 513, in process_one\\n    await dispatch(*args)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 418, in dispatch_shell\\n    await result\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 758, in execute_request\\n    reply_content = await reply_content\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 426, in do_execute\\n    res = shell.run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\\n    return super().run_cell(*args, **kwargs)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\\n    result = self._run_cell(\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\\n    result = runner(coro)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\\n    coro.send(None)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\\n    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\\n    if await self.run_code(code, result, async_=asy):\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\\n    exec(code_obj, self.user_global_ns, self.user_ns)\\n', '  File \"/tmp/ipykernel_2726929/158012258.py\", line 1, in <module>\\n    from rl_jailbreak.models.model import load_generator, load_target, load_reward\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/__init__.py\", line 1, in <module>\\n    from .reward_model import ToxicityModel\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/data/nzxyin/rl_jailbreak/rl_jailbreak/models/reward_model.py\", line 2, in <module>\\n    from transformers import AutoTokenizer, AutoModelForSequenceClassification\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/__init__.py\", line 26, in <module>\\n    from . import dependency_versions_check\\n', '  File \"<frozen importlib._bootstrap>\", line 1078, in _handle_fromlist\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/dependency_versions_check.py\", line 16, in <module>\\n    from .utils.versions import require_version, require_version_core\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/__init__.py\", line 31, in <module>\\n    from .generic import (\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/transformers/utils/generic.py\", line 432, in <module>\\n    import torch.utils._pytree as _torch_pytree\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 992, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/__init__.py\", line 1146, in <module>\\n    _C._initExtension(manager_path())\\n', '  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\\n', '  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\\n', '  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\\n', '  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\\n', '  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 197, in <module>\\n    _lazy_call(_check_capability)\\n', '  File \"/home/nzxyin/miniconda3/envs/rl_jailbreak/lib/python3.10/site-packages/torch/cuda/__init__.py\", line 195, in _lazy_call\\n    _queued_calls.append((callable, traceback.format_stack()))\\n']"
     ]
    }
   ],
   "source": [
    "generator = load_generator(\"gpt2-medium\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "import gc\n",
    "import torch\n",
    "torch.cuda.empty_cache()\n",
    "# del generator\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "adv_rlaif",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
